variables:
  CI_PHP_BEFORE_INSTALL_SCRIPT: composer config version 1.999999

include:
  - project: mahalux/php-ci
    file: /templates/shared.yml
  - project: mahalux/php-ci
    file: /templates/php-cs.yml
  - project: mahalux/php-ci
    file: /templates/php-phpstan.yml
  - project: mahalux/php-ci
    file: /templates/php-phpunit.yml
